bencompton/jest-cucumber

package-lock.json, package.json
The lower version of `jest@23.3.0` resolves to a version `braces` that produces an error during audit - https://www.npmjs.com/advisories/786.
The issue is fixed in `jest@24.1.0`.
This fix should be high priority. If `npm run audit` is a quality gate during build, this will fail the build.
=> Upgrade jest, babel-jest & @types/node

examples/typescript/specs/features/scenario-outlines.feature, examples/typescript/specs/step-definitions/scenario-outlines.steps.ts, src/parsed-feature-loading.ts
This PR fixes an issue with having multiple dynamic keys in scenario outline. The previous behavior was to look only for one key, and with a too permissive regexp. Thus resulting in bad scenario names :
- The regexp was `<(.*)>`
- Given a title : `"some title <withOneDynamicVariable> and <anOtherDynamicVariable> in it"` and an exampleTableRow : `{ withOneDynamicVariable: 'foo', anOtherDynamicVariable: 'bar' }`
- The generated title is "some title foo in it", because the regex matches : `"<withOneDynamicVariable> and <anOtherDynamicVariable>"`
The new regexp is now `/(\S*)/g` since you can't have space in gherkin variable's name.
=> enable multiple dynamic key replacements in scenario outline

src/parsed-feature-loading.ts
**The issue**: Because of our setup, tracing the directory which calls the loadFeature function seems impossible. The callsites() call in our case returns an array of one, requesting the second value returns undefined and the getFileName call causes Error: Cannot read property 'getFileName' of undefined.
**The fix**: Check if callsites()[1] exists before calling getFileName() and use fallback value otherwise.
=> Fix fallback when callsites does not include caller directory

examples/ecmascript/package.json, examples/ecmascript/specs/features/scenario-outlines.feature
When using the ECMAScript found that when the update for table <title> was added this section didn't match the step_definitions with feature file. Also, add a simple `jest -verbose` script to the package.
=> Scenario outline title fix

README.md, docs/ScenarioOutlines.md, docs/UsingDocstrings.md, examples/ecmascript/specs/features/more-scenario-outlines.feature, examples/ecmascript/specs/features/using-docstrings.feature, examples/ecmascript/specs/step-definitions/more-scenario-outlines.steps.js, examples/ecmascript/specs/step-definitions/using-docstrings.steps.js, examples/ecmascript/src/certificate-factory.js, examples/ecmascript/src/series-solver.js, examples/typescript/specs/features/more-scenario-outlines.feature, examples/typescript/specs/features/using-docstrings.feature, examples/typescript/specs/step-definitions/more-scenario-outlines.steps.ts, examples/typescript/specs/step-definitions/using-docstrings.steps.ts, examples/typescript/src/certificate-factory.ts, examples/typescript/src/series-solver.ts, src/parsed-feature-loading.ts
Figured I might as well just create the pull request, I can always squash the commits later.
I've added what I hope is a solution to using Docstrings with Scenario Outlines as described in #7 and #79. The implementation is concentrated to `src/parsed-feature-loading.ts` I also added a couple of examples for TypeScript and ECMAScript to illustrate the new functionality (it was previously not possible to use Docstrings and Scenario Outlines together).
Have a look and ping me if there are any concerns.
=> Support for docstrings in scenario outlines

package-lock.json, src/feature-definition-creation.ts
Some hours ago I opened [an issue](https://github.com/bencompton/jest-cucumber/issues/83), I decided to help with this.
The "test" function now optionally accept the timeout option to control async operations. The default value is `5000`
Example:
**Tests**: npm scripts has been run without any error.
Hope this get merged.
=> Added timeout option to add more control over async operations

examples/typescript/specs/features/language.feature, examples/typescript/specs/step-definitions/language.steps.ts, src/parsed-feature-loading.ts
Added language support for when language is set other then the default 'en'.
Using `Gherkins.dialects()` to map the other language it's keywords to en-keywords.
Added a tests that covers most cases.
Also see: https://github.com/bencompton/jest-cucumber/issues/107
=> Language support

package-lock.json, package.json, src/parsed-feature-loading.ts, tsconfig.json
The 'gherkin' npm package has been deprecated (even though it's not yet marked as such, see https://github.com/cucumber/cucumber/issues/1421). This PR updates it to the newest version in order to benefit from parser updates.
=> build: migrate to @cucumber/gherkin npm package

docs/ReusingStepDefinitions.md
I fixed a tiny typo, so that the docs match what the function is called in Jest.
=> docs: ReusingStepDefinitions: change case: `BeforeEach` -> `beforeEach`

README.md, package-lock.json, package.json
Hello,
This pull request includes several changes to the `package.json` file to improve the library's compatibility and efficiency:
1. **Move from `jest` to `peerDependencies`**: This change allows users of this library to use their own version of Jest, increasing compatibility with different projects.
2. **Move from `@types/jest` to `optionalPeerDependencies`**: Similar to the above, this allows consumers to optionally use their own TypeScript typings for Jest.
3. **Type libraries moved to `devDependencies`**: This prevents these libraries from being installed by consumers of this library, thus reducing unnecessary installations.
These changes are intended to make this library more efficient and compatible with a wider range of projects.
Please review these changes and provide your …
=> Refactoring package.json for Better Compatibility and Efficiency

CODE_OF_CONDUCT.md, LICENSE, package.json
Dear,
I'm opening this pull request to resolve an inconsistency I noticed in the project. The license mentioned in the `package.json` file was MIT, while the license file was Apache 2.0. To solve this problem, I updated the `package.json` file to reflect the Apache 2.0 license.
In addition, I noticed that your name didn't appear in the license file, so I took the liberty of updating it too.
Following your addition of a contributing.md, I've generated a code of conduct from [https://bttger.github.io/contributing-gen-web/](https://bttger.github.io/contributing-gen-web/) and propose to add it to the project. I think it will help guide interactions and enforce community standards.
Best.
=> License Correction and Code of Conduct Addition

examples/typescript/specs/step-definitions/auto-step-binding-outline.steps.ts, src/automatic-step-binding.ts
Fixes #101 
Opened a new PR on current master in favor of https://github.com/bencompton/jest-cucumber/pull/142.
To try and install this version locally, run
```sh
npm install --save-dev Papooch/jest-cucumber#dist
```
---
1) Checkout the firs commit, run `npm run test`
2) See test fail with `Feature file has a scenario titled "Selling an <Item> at $<Amount>", but no match found in step definitions.`
3) Checkout second commit, see all tests pass.
=> Fix scenario outline title placeholder to work with autoBindSteps

.github/workflows/npm-publish.yml, package-lock.json, package.json
Hello @bencompton ,
Sorry for the direct mention, but there's a big problem with the github publish action. The build step is missing, which means the dist folder isn't published to the npm registry.\
This makes the library unusable.
I suggest this quick fix to quickly fix and republish a patched version.
=> Fix no build before npm publish

.github/workflows/npm-publish.yml
The github action you set up https://github.com/pascalgn/npm-publish-action/blob/master/Dockerfile uses version 12 of node with yarn 1.
So I wonder if yarn isn't causing the problem because it's used by default.
So I've configured it to use npm as you were able to use it locally without any problems, which should work, or so I hope.
I'm really sorry for all the problems, it's the first time that using husky has caused me problems.
As a last resort we could temporarily remove husky until we find a permanent solution.
=> Use npm to publish package

.github/workflows/run-tests.yaml, .husky/commit-msg, CONTRIBUTING.md, package-lock.json, package.json
Hello,
This PR introduces `commitlint` configured with the `conventional commit` standard. The aim is to ensure that all commits adhere to a consistent style for better code management and readability, as indicated in issue #195.
Two levels of verification have been added:
1. Local verification through `husky commit-msg`, which checks each commit made locally.
2. A build workflow verification that checks all commits within a PR (only on a PR).
The build workflow has been revised for easier review, separating different stages (lint, test, build) into distinct steps. A package-lock verification stage has also been added. This was motivated by noticing frequent discrepancies between `package.json` and `package-lock.json` in several projects I've worked on.
The documentation has been updated …
=> Implementing Commitlint with Conventional Commit Configuration

docs/AutomaticStepBinding.md, examples/typescript/specs/step-definitions/auto-binding/auto-step-binding-beverage-vending.steps.ts, examples/typescript/specs/step-definitions/auto-binding/auto-step-binding.steps.ts, src/automatic-step-binding.ts
This PR updates the `autoBindSteps` function to support a single `.feature` file. 
The aim is to maintain Jest's parallelization capabilities, by making it possible to create a steps file with `autoBindSteps`.
=> Enhancement: Update autoBindSteps to Support Single .feature File

examples/typescript/specs/step-definitions/auto-binding/auto-step-binding-snack-vending-use-context.steps.ts, src/automatic-step-binding.ts, src/feature-definition-creation.ts, src/index.ts
This PR introduces the ability to share context between `steps` and `stepDefinition` files during test execution. This is achieved by using the context to load the necessary information.
Here is an example of how this works:
In the `stepDefinition` function, we initialise a `new VendingMachine()` via `beforeEach`. This allows it to be added to the context, which can then be used directly in steps or even in other `stepDefinition` files.
```typescript
// specs/step-definitions/global-vending-machine-steps.ts
import { StepDefinitionsWithContext } from 'jest-cucumber';
import { VendingMachine } from '../src/vending-machine';
type Context = {
vendingMachine: VendingMachine;
};
export const globalVendingMachineSteps: StepDefinitionsWithContext<Context> = ({ given, and, when, then, context }) …
```
=> Add Shared Context Capability to Step Definitions

package.json, specs/parsed-feature-loading.test.ts, src/parsed-feature-loading.ts
This PR corrects a regression present since version 4. 
The problem concerned the `loadFeature` function, which threw an exception when `loadRelativePath` was set to `true` via `setJestCucumberConfiguration` in the setupTest file.
=> Fix regression in loadFeature now corrected to consider global options for relative feature file loading

package-lock.json, package.json, src/parsed-feature-loading.ts
Closes #214
* Upgraded `@cucumber/gherkin` from version 17 to version 28. 
* Updated code to maintain compatibility with existing features. 
All breaking changes on the `@cucumber/gherkin` dependency were introduced in v18 and v19, so technically the code is compatible with versions 19 through 28 of the dependency, however I left the latest version in case someone wants to implement any of the new features and to have sub-dependencies more up to date.
There are no breaking changes for users of this project, I already tested with one of my projects and no changes are needed for it to work the same as before.
=> feat(deps): upgrade @cucumber/gherkin to v28

docs/AsynchronousSteps.md, examples/typescript/specs/features/using-latest-gherkin-keywords.feature, examples/typescript/specs/step-definitions/using-latest-gherkin-keywords.steps.ts, examples/typescript/src/calculator.ts, examples/vitest/specs/features/using-latest-gherkin-keywords.feature, examples/vitest/specs/step-definitions/using-latest-gherkin-keywords.steps.ts, examples/vitest/src/calculator.ts, specs/features/steps/step-execution.feature, specs/step-definitions/step-execution.steps.ts, specs/test-data/step-execution.ts, src/feature-definition-creation.ts, src/models.ts, src/parsed-feature-loading.ts
Closes #16 
* Added compatibility for done callback usage in functions for steps
* Added tests for the done callback usage
* Fixed a unit test that was not properly configured (conflicted with the new changes)
* Updated the type of the `stepArgument` property of ParsedStep to better reflect the possible values.
* Updated documentation with the done callback information
Any issue please let me know, thanks
=> feat: add basic done callback compatibility in steps

src/index.ts
I ended up wrapping `#loadFeature` and had to expose its options types. And I'd rather import those from "`jest-cucumber`" instead of "`jest-cucumber/dist/...`" or repeat its definition in my program... :)
=> Exposing few symbols from configuration

src/tag-filtering.ts
Fixing an issue when `tagFilter` value in `setJestCucumberConfiguration` was set with dot characters, e.g.
```js
setJestCucumberConfiguration({ tagFilter: '@10.2.2_1' });
```
causing following error
```
Error: Could not parse tag filter "@10.2.2_1"
❯ convertTagFilterExpressionToFunction node_modules/jest-cucumber/src/tag-filtering.ts:40:11
❯ checkIfScenarioMatchesTagFilter node_modules/jest-cucumber/src/tag-filtering.ts:59:25
❯ setScenarioSkipped node_modules/jest-cucumber/src/tag-filtering.ts:67:32
❯ node_modules/jest-cucumber/src/tag-filtering.ts:84:61
❯ applyTagFilters node_modules/jest-cucumber/src/tag-filtering.ts:84:45
❯ defineFeature node_modules/jest-cucumber/src/feature-definition-creation.ts:383:63
❯ node_modules/jest-cucumber/src/automatic-step-binding.ts:44:7
❯ …
```
=> Adding additional characters to tag filter regex
